name: Deploy to GitHub Pages

on:
  push:
    branches:
      - bushido-webpack

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: yarn install

    - name: Build and deploy to GitHub Pages
      run: |
        npm run build:prod
        git config user.name "${{ GITHUB_ACTOR }}"
        git config user.email "${{ GITHUB_ACTOR_EMAIL }}"
        git switch -c gh-pages
        git add .
        git commit -m "Auto deploy to GitHub Pages"
        git pull origin gh-pages --rebase
        git push --set-upstream origin gh-pages